spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
  cloud:
    stream:
      gcp:
        pubsub:
          producer:
            autoCreateResources: false

      bindings:
        topic0:
          destination: projects/jkwng-pubsub-spring-boot-a76c/topics/topic-2480
        #topic1:
        #  destination: projects/jkwng-pubsub-spring-boot-a76c/topics/topic-da76
        #topic2:
        #  destination: projects/jkwng-pubsub-spring-boot-a76c/topics/topic-f7ab


